model:
  target: rdm.models.diffusion.ddpm.RDM
  params:
    linear_start: 0.0015
    linear_end: 0.0195
    num_timesteps_cond: 1
    log_every_t: 200
    timesteps: 1000
    first_stage_key: image
    cond_stage_key: class_label
    image_size: 1
    channels: 256
    cond_stage_trainable: true
    conditioning_key: crossattn
    parameterization: x0
    unet_config:
      target: rdm.modules.diffusionmodules.latentmlp.SimpleMLP
      params:
        in_channels: 256
        time_embed_dim: 256
        model_channels: 1536
        bottleneck_channels: 1536
        out_channels: 256
        num_res_blocks: 12
    pretrained_enc_config:
      params:
        pretrained_enc_arch: mocov3_vit_large
        pretrained_enc_path: pretrained_enc_ckpts/mocov3/vitl.pth.tar
        proj_dim: 256
        pretrained_enc_withproj: True
    cond_stage_config:
      target: rdm.modules.encoders.modules.ClassEmbedder
      params:
        embed_dim: 512
        n_classes: 1
        key: class_label
